WITH defs AS (
  SELECT * FROM (VALUES
    ('derived_root','Derived Metrics',NULL,'04',4,false,false,NULL),
    ('liquidity_ratios','Liquidity Ratios','derived_root','0401',10,false,false,NULL),
    ('leverage_ratios','Leverage Ratios','derived_root','0402',20,false,false,NULL),
    ('profitability_ratios','Profitability Ratios','derived_root','0403',30,false,false,NULL),
    ('efficiency_ratios','Efficiency Ratios','derived_root','0404',40,false,false,NULL),
    ('cashflow_ratios','Cashflow Ratios','derived_root','0405',50,false,false,NULL),
    ('valuation_models','Valuation Models','derived_root','0406',60,false,false,NULL),
    ('per_share_metrics','Per Share Metrics','derived_root','0407',70,false,false,NULL),

    ('working_capital','Working Capital','liquidity_ratios','040101',101,false,true,'current_assets - current_liabilities'),
    ('current_ratio','Current Ratio','liquidity_ratios','040102',102,false,true,'current_assets / current_liabilities'),
    ('quick_assets','Quick Assets','liquidity_ratios','040103',103,false,true,'current_assets - inventories_total - prepaid_expenses - advances_to_suppliers'),
    ('quick_ratio','Quick Ratio','liquidity_ratios','040104',104,false,true,'quick_assets / current_liabilities'),
    ('cash_ratio','Cash Ratio','liquidity_ratios','040105',105,false,true,'cash_and_cash_equivalents / current_liabilities'),
    ('working_capital_to_sales','Working Capital To Sales','liquidity_ratios','040106',106,false,true,'working_capital / revenue_from_operations'),
    ('defensive_interval_ratio','Defensive Interval Ratio','liquidity_ratios','040107',107,false,true,NULL),

    ('total_debt','Total Debt','leverage_ratios','040201',201,false,true,'long_term_borrowings + short_term_borrowings + current_portion_long_term_debt + lease_liabilities_non_current'),
    ('net_debt','Net Debt','leverage_ratios','040202',202,false,true,'total_debt - cash_and_cash_equivalents'),
    ('debt_to_equity','Debt To Equity','leverage_ratios','040203',203,false,true,'total_debt / equity'),
    ('debt_to_assets','Debt To Assets','leverage_ratios','040204',204,false,true,'total_debt / total_assets'),
    ('debt_to_capital','Debt To Capital','leverage_ratios','040205',205,false,true,'total_debt / (total_debt + equity)'),
    ('equity_ratio','Equity Ratio','leverage_ratios','040206',206,false,true,'equity / total_assets'),
    ('financial_leverage','Financial Leverage','leverage_ratios','040207',207,false,true,'total_assets / equity'),
    ('interest_coverage','Interest Coverage','leverage_ratios','040208',208,false,true,'ebit / finance_cost_section'),
    ('ebitda_interest_coverage','EBITDA Interest Coverage','leverage_ratios','040209',209,false,true,'ebitda / finance_cost_section'),
    ('net_debt_to_ebitda','Net Debt To EBITDA','leverage_ratios','040210',210,false,true,'net_debt / ebitda'),

    ('tax_rate_effective','Effective Tax Rate','profitability_ratios','040301',301,false,true,'(current_tax_expense + deferred_tax_expense) / profit_before_tax'),
    ('nopat','NOPAT','profitability_ratios','040302',302,false,true,'ebit * (1 - tax_rate_effective)'),
    ('invested_capital','Invested Capital','profitability_ratios','040303',303,false,true,'equity + total_debt - cash_and_cash_equivalents'),
    ('gross_margin','Gross Margin','profitability_ratios','040304',304,false,true,'gross_profit / revenue_from_operations'),
    ('ebitda_margin','EBITDA Margin','profitability_ratios','040305',305,false,true,'ebitda / revenue_from_operations'),
    ('ebit_margin','EBIT Margin','profitability_ratios','040306',306,false,true,'ebit / revenue_from_operations'),
    ('pretax_margin','Pre Tax Margin','profitability_ratios','040307',307,false,true,'profit_before_tax / revenue_from_operations'),
    ('net_margin','Net Margin','profitability_ratios','040308',308,false,true,'net_profit / revenue_from_operations'),
    ('roa','Return On Assets','profitability_ratios','040309',309,false,true,'net_profit / total_assets'),
    ('roe','Return On Equity','profitability_ratios','040310',310,false,true,'net_profit / equity'),
    ('roce','Return On Capital Employed','profitability_ratios','040311',311,false,true,'ebit / (equity + long_term_borrowings + lease_liabilities_non_current)'),
    ('roic','Return On Invested Capital','profitability_ratios','040312',312,false,true,'nopat / invested_capital'),

    ('asset_turnover','Asset Turnover','efficiency_ratios','040401',401,false,true,'revenue_from_operations / total_assets'),
    ('fixed_asset_turnover','Fixed Asset Turnover','efficiency_ratios','040402',402,false,true,'revenue_from_operations / property_plant_equipment'),
    ('inventory_turnover','Inventory Turnover','efficiency_ratios','040403',403,false,true,'cost_of_materials_consumed / inventories_total'),
    ('receivables_turnover','Receivables Turnover','efficiency_ratios','040404',404,false,true,'revenue_from_operations / net_trade_receivables'),
    ('payables_turnover','Payables Turnover','efficiency_ratios','040405',405,false,true,'cost_of_materials_consumed / (trade_payables_micro_small + trade_payables_other)'),
    ('working_capital_turnover','Working Capital Turnover','efficiency_ratios','040406',406,false,true,'revenue_from_operations / working_capital'),
    ('days_inventory_outstanding','Days Inventory Outstanding','efficiency_ratios','040407',407,false,true,'365 / inventory_turnover'),
    ('days_sales_outstanding','Days Sales Outstanding','efficiency_ratios','040408',408,false,true,'365 / receivables_turnover'),
    ('days_payables_outstanding','Days Payables Outstanding','efficiency_ratios','040409',409,false,true,'365 / payables_turnover'),
    ('cash_conversion_cycle','Cash Conversion Cycle','efficiency_ratios','040410',410,false,true,'days_inventory_outstanding + days_sales_outstanding - days_payables_outstanding'),

    ('operating_cashflow_to_sales','Operating Cashflow To Sales','cashflow_ratios','040501',501,false,true,'net_cash_from_operating_activities / revenue_from_operations'),
    ('operating_cashflow_to_net_income','Operating Cashflow To Net Income','cashflow_ratios','040502',502,false,true,'net_cash_from_operating_activities / net_profit'),
    ('free_cash_flow','Free Cash Flow','cashflow_ratios','040503',503,false,true,'net_cash_from_operating_activities - purchase_of_property_plant_equipment - purchase_of_intangible_assets'),
    ('free_cashflow_margin','Free Cashflow Margin','cashflow_ratios','040504',504,false,true,'free_cash_flow / revenue_from_operations'),
    ('cash_flow_to_debt','Cash Flow To Debt','cashflow_ratios','040505',505,false,true,'net_cash_from_operating_activities / total_debt'),
    ('cash_interest_coverage','Cash Interest Coverage','cashflow_ratios','040506',506,false,true,'net_cash_from_operating_activities / interest_paid'),
    ('fcf_to_net_income','FCF To Net Income','cashflow_ratios','040507',507,false,true,'free_cash_flow / net_profit'),

    ('market_price_per_share','Market Price Per Share','valuation_models','040601',601,false,false,NULL),
    ('shares_outstanding','Shares Outstanding','valuation_models','040602',602,false,false,NULL),
    ('enterprise_value_manual','Enterprise Value Manual','valuation_models','040603',603,false,false,NULL),
    ('market_cap','Market Capitalization','valuation_models','040604',604,false,true,'market_price_per_share * shares_outstanding'),
    ('enterprise_value_calc','Enterprise Value','valuation_models','040605',605,false,true,'market_cap + total_debt - cash_and_cash_equivalents'),
    ('pe_ratio','P E Ratio','valuation_models','040606',606,false,true,'market_price_per_share / eps_basic'),
    ('pb_ratio','P B Ratio','valuation_models','040607',607,false,true,'market_price_per_share / book_value_per_share'),
    ('ps_ratio','P S Ratio','valuation_models','040608',608,false,true,'market_price_per_share / sales_per_share'),
    ('ev_to_ebitda','EV To EBITDA','valuation_models','040609',609,false,true,'enterprise_value_calc / ebitda'),
    ('ev_to_sales','EV To Sales','valuation_models','040610',610,false,true,'enterprise_value_calc / revenue_from_operations'),
    ('ev_to_ebit','EV To EBIT','valuation_models','040611',611,false,true,'enterprise_value_calc / ebit'),
    ('earnings_yield','Earnings Yield','valuation_models','040612',612,false,true,'eps_basic / market_price_per_share'),
    ('fcf_yield','FCF Yield','valuation_models','040613',613,false,true,'fcf_per_share / market_price_per_share'),
    ('price_to_ocf','Price To OCF','valuation_models','040614',614,false,true,'market_price_per_share / operating_cashflow_per_share'),

    ('eps_basic','EPS Basic','per_share_metrics','040701',701,false,true,'net_profit / shares_outstanding'),
    ('book_value_per_share','Book Value Per Share','per_share_metrics','040702',702,false,true,'equity / shares_outstanding'),
    ('sales_per_share','Sales Per Share','per_share_metrics','040703',703,false,true,'revenue_from_operations / shares_outstanding'),
    ('operating_cashflow_per_share','Operating Cashflow Per Share','per_share_metrics','040704',704,false,true,'net_cash_from_operating_activities / shares_outstanding'),
    ('fcf_per_share','FCF Per Share','per_share_metrics','040705',705,false,true,'free_cash_flow / shares_outstanding')
  ) AS t(code, name, parent_code, order_code, display_order, is_required, is_calculated, formula)
)
INSERT INTO financial_line_items (
  code,
  name,
  parent_id,
  statement_type,
  order_code,
  display_order,
  is_required,
  is_calculated,
  formula,
  created_at,
  updated_at
)
SELECT
  d.code,
  d.name,
  parent.id,
  'derived'::statement_type,
  d.order_code,
  d.display_order,
  d.is_required,
  d.is_calculated,
  d.formula,
  now(),
  now()
FROM defs d
LEFT JOIN financial_line_items parent ON parent.code = d.parent_code
ON CONFLICT (code) DO UPDATE
SET
  name = EXCLUDED.name,
  parent_id = EXCLUDED.parent_id,
  statement_type = EXCLUDED.statement_type,
  order_code = EXCLUDED.order_code,
  display_order = EXCLUDED.display_order,
  is_required = EXCLUDED.is_required,
  is_calculated = EXCLUDED.is_calculated,
  formula = EXCLUDED.formula,
  updated_at = now();
