import { model } from "@medusajs/framework/utils"

export const CompanyRecord = model.define("company_record", {
  id: model.id().primaryKey(),
  company_id: model.text(),
  company_name: model.text(),
  isin: model.text(),
  cin: model.text(),
  sector: model.text(),
  industry: model.text(),
  description: model.text(),
  listing_status: model.text(),
  overview_data: model.text(),
  ratios_data: model.text(),
  trends_data: model.text(),
  synced_at: model.text(),
  market_cap: model.text(),
  share_type: model.text(),
  lot_size: model.text(),
  face_value: model.text(),
  depository: model.text(),
  pan_number: model.text(),
  rta: model.text(),
  total_shares: model.text(),
  fifty_two_week_high: model.text(),
  fifty_two_week_low: model.text(),
  founded: model.text(),
  headquarters: model.text(),
  valuation: model.text(),
  pe_ratio: model.text(),
  pb_ratio: model.text(),
  roe_value: model.text(),
  debt_to_equity: model.text(),
  book_value: model.text(),
  // Snapshot cache (populated from Calcula). Large JSON blobs stored as text.
  statements_snapshot: model.text(),
  statements_version: model.text(),
  price_snapshot: model.text(),
  price_version: model.text(),
  // Phase 3 — editorial news events + timeline.
  news_snapshot: model.text(),
  news_version: model.text(),
  // Phase 4/5 — bundled editorial blob (pros/cons + company overview).
  editorial_snapshot: model.text(),
  editorial_version: model.text(),
  content_updated_at: model.text(),
  last_accessed_at: model.text(),
})
